Fri Jan 31 23:29:57 CET 2025 : Apache Derby Network Server - 10.17.1.0 - (1913217) started and ready to accept connections on port 1527
----------------------------------------------------------------
Fri Jan 31 23:29:57 CET 2025:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.17.1.0 - (1913217): instance a816c00e-0194-be7c-3068-ffff992e9aae 
on database directory C:\Users\piter\Desktop\Git_repos\Sudoku\DB\lab1 with class loader jdk.internal.loader.ClassLoaders$AppClassLoader@33909752 
Loaded from file:/C:/Users/piter/Desktop/Git_repos/Sudoku/db-derby-10.17.1.0-bin/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=21.0.4+8-LTS-274
user.dir=C:\Users\piter\Desktop\Git_repos\Sudoku\db-derby-10.17.1.0-bin
os.name=Windows 11
os.arch=amd64
os.version=10.0
derby.system.home=C:\Users\piter\Desktop\Git_repos\Sudoku\DB
Database Class Loader started - derby.database.classpath=''
----------------------------------------------------------------
Fri Jan 31 23:30:03 CET 2025:
Shutting down instance a816c00e-0194-be7c-3068-ffff992e9aae on database directory C:\Users\piter\Desktop\Git_repos\Sudoku\DB\lab1 with class loader jdk.internal.loader.ClassLoaders$AppClassLoader@33909752 
Fri Jan 31 23:30:03 CET 2025 Thread[#24,DRDAConnThread_2,5,main] (DATABASE = lab1), (DRDAID = {2}), Database 'lab1' shutdown.
Fri Jan 31 23:30:09 CET 2025 Thread[#24,DRDAConnThread_2,5,main] Cleanup action starting
java.sql.SQLException: Database 'lab' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:115)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:141)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Util.java:225)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Util.java:220)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(EmbedConnection.java:3208)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(EmbedConnection.java:767)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:437)
	at org.apache.derby.iapi.jdbc.InternalDriver.getNewEmbedConnection(InternalDriver.java:629)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:295)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:921)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(EmbeddedDriver.java:125)
	at org.apache.derby.impl.drda.Database.makeConnection(Database.java:253)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(DRDAConnThread.java:1474)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(DRDAConnThread.java:1424)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(DRDAConnThread.java:3378)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(DRDAConnThread.java:1208)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(DRDAConnThread.java:1008)
	at org.apache.derby.impl.drda.DRDAConnThread.run(DRDAConnThread.java:298)
Caused by: ERROR XJ004: Database 'lab' not found.
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:299)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(SQLExceptionFactory.java:170)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:75)
	... 17 more
============= begin nested exception, level (1) ===========
ERROR XJ004: Database 'lab' not found.
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:299)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(SQLExceptionFactory.java:170)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:75)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:141)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Util.java:225)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Util.java:220)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(EmbedConnection.java:3208)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(EmbedConnection.java:767)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:437)
	at org.apache.derby.iapi.jdbc.InternalDriver.getNewEmbedConnection(InternalDriver.java:629)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:295)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:921)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(EmbeddedDriver.java:125)
	at org.apache.derby.impl.drda.Database.makeConnection(Database.java:253)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(DRDAConnThread.java:1474)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(DRDAConnThread.java:1424)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(DRDAConnThread.java:3378)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(DRDAConnThread.java:1208)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(DRDAConnThread.java:1008)
	at org.apache.derby.impl.drda.DRDAConnThread.run(DRDAConnThread.java:298)
============= end nested exception, level (1) ===========
Cleanup action completed
Fri Jan 31 23:30:09 CET 2025 Thread[#24,DRDAConnThread_2,5,main] (DATABASE = lab), (DRDAID = {3}), Database 'lab' not found.
----------------------------------------------------------------
Fri Jan 31 23:30:22 CET 2025:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.17.1.0 - (1913217): instance e66540fa-0194-be7c-3068-ffff992e9aae 
on database directory C:\Users\piter\Desktop\Git_repos\Sudoku\DB\lab with class loader jdk.internal.loader.ClassLoaders$AppClassLoader@33909752 
Loaded from file:/C:/Users/piter/Desktop/Git_repos/Sudoku/db-derby-10.17.1.0-bin/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=21.0.4+8-LTS-274
user.dir=C:\Users\piter\Desktop\Git_repos\Sudoku\db-derby-10.17.1.0-bin
os.name=Windows 11
os.arch=amd64
os.version=10.0
derby.system.home=C:\Users\piter\Desktop\Git_repos\Sudoku\DB
Database Class Loader started - derby.database.classpath=''
Fri Jan 31 23:37:20 CET 2025 Thread[#34,DRDAConnThread_3,5,main] Cleanup action starting
java.sql.SQLException: Database 'Sudoku' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:115)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:141)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Util.java:225)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Util.java:220)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(EmbedConnection.java:3208)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(EmbedConnection.java:767)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:437)
	at org.apache.derby.iapi.jdbc.InternalDriver.getNewEmbedConnection(InternalDriver.java:629)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:295)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:921)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(EmbeddedDriver.java:125)
	at org.apache.derby.impl.drda.Database.makeConnection(Database.java:253)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(DRDAConnThread.java:1474)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(DRDAConnThread.java:1424)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(DRDAConnThread.java:3378)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(DRDAConnThread.java:1208)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(DRDAConnThread.java:1008)
	at org.apache.derby.impl.drda.DRDAConnThread.run(DRDAConnThread.java:298)
Caused by: ERROR XJ004: Database 'Sudoku' not found.
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:299)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(SQLExceptionFactory.java:170)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:75)
	... 17 more
============= begin nested exception, level (1) ===========
ERROR XJ004: Database 'Sudoku' not found.
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:299)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(SQLExceptionFactory.java:170)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:75)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:141)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Util.java:225)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Util.java:220)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(EmbedConnection.java:3208)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(EmbedConnection.java:767)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:437)
	at org.apache.derby.iapi.jdbc.InternalDriver.getNewEmbedConnection(InternalDriver.java:629)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:295)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:921)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(EmbeddedDriver.java:125)
	at org.apache.derby.impl.drda.Database.makeConnection(Database.java:253)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(DRDAConnThread.java:1474)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(DRDAConnThread.java:1424)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(DRDAConnThread.java:3378)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(DRDAConnThread.java:1208)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(DRDAConnThread.java:1008)
	at org.apache.derby.impl.drda.DRDAConnThread.run(DRDAConnThread.java:298)
============= end nested exception, level (1) ===========
Cleanup action completed
Fri Jan 31 23:37:20 CET 2025 Thread[#34,DRDAConnThread_3,5,main] (DATABASE = Sudoku), (DRDAID = {7}), Database 'Sudoku' not found.
----------------------------------------------------------------
Fri Jan 31 23:37:29 CET 2025:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.17.1.0 - (1913217): instance a54dc20b-0194-be7c-3068-ffff992e9aae 
on database directory C:\Users\piter\Desktop\Git_repos\Sudoku\DB\sudoku with class loader jdk.internal.loader.ClassLoaders$AppClassLoader@33909752 
Loaded from file:/C:/Users/piter/Desktop/Git_repos/Sudoku/db-derby-10.17.1.0-bin/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=21.0.4+8-LTS-274
user.dir=C:\Users\piter\Desktop\Git_repos\Sudoku\db-derby-10.17.1.0-bin
os.name=Windows 11
os.arch=amd64
os.version=10.0
derby.system.home=C:\Users\piter\Desktop\Git_repos\Sudoku\DB
Database Class Loader started - derby.database.classpath=''
----------------------------------------------------------------
Sat Feb 01 00:57:57 CET 2025: Shutting down Derby engine
----------------------------------------------------------------
Sat Feb 01 00:57:57 CET 2025:
Shutting down instance a54dc20b-0194-be7c-3068-ffff992e9aae on database directory C:\Users\piter\Desktop\Git_repos\Sudoku\DB\sudoku with class loader jdk.internal.loader.ClassLoaders$AppClassLoader@33909752 
----------------------------------------------------------------
Sat Feb 01 00:57:57 CET 2025:
Shutting down instance e66540fa-0194-be7c-3068-ffff992e9aae on database directory C:\Users\piter\Desktop\Git_repos\Sudoku\DB\lab with class loader jdk.internal.loader.ClassLoaders$AppClassLoader@33909752 
----------------------------------------------------------------
